local console_commands = require("scripts.utilities.commands")
local debug = require("scripts.utilities.debug")
local events = require("scripts.core.events")

-- Event wiring.
local function register_runtime_events()
	script.on_event(defines.events.on_cutscene_cancelled, events.on_cutscene_cancelled)
	script.on_event(defines.events.on_entity_damaged, events.on_entity_damaged)
	script.on_event(defines.events.on_entity_died, events.on_entity_died)
	script.on_event(defines.events.on_gui_click, events.on_gui_click)
	script.on_event(defines.events.on_gui_closed, events.on_gui_closed)
	script.on_event(defines.events.on_gui_confirmed, events.on_gui_confirmed)
	script.on_event(defines.events.on_gui_text_changed, events.on_gui_text_changed)
	script.on_event(defines.events.on_gui_switch_state_changed, events.on_gui_switch_state_changed)
	script.on_event(defines.events.on_marked_for_deconstruction, events.on_marked_for_deconstruction)
	script.on_event(defines.events.on_player_created, events.on_player_created)
	script.on_event(defines.events.on_research_finished, events.on_research_finished)
	script.on_event(defines.events.on_player_mined_entity, events.on_player_mined_entity)
	script.on_event(defines.events.on_player_main_inventory_changed, events.on_player_main_inventory_changed)
	script.on_event(defines.events.on_built_entity, events.on_built_entity)
	script.on_event(defines.events.on_unit_group_finished_gathering, events.on_unit_group_finished_gathering)
	script.on_event(defines.events.on_tick, events.on_tick)
	script.on_event("pet-close-gui", events.pet_close_gui)
	script.on_event("pet-interact", events.pet_interact)
	script.on_event("pet-open-gui", events.pet_open_gui)
end

script.on_init(function()
	events.on_init()
	register_runtime_events()
end)

script.on_load(function()
	events.on_load()
	register_runtime_events()
end)

script.on_configuration_changed(function(cfg)
	events.on_configuration_changed(cfg)
end)
