require("prototypes.sprites.pet_emotes")
require("prototypes.units.pet_animations")
require("prototypes.units.pet_biter")
require("prototypes.units.pet_input")
require("prototypes.items.pet_spitter_remains")
require("prototypes.items.pet_biter_remains")
require("prototypes.items.pet_guardians")
require("prototypes.sounds")