local NEEDS_CONSTANTS = {
	HUNGER_INCREMENT = 1, -- Hunger added every interval.
	HUNGER_INTERVAL = 60 * 30, -- 30 seconds between intervals.

	THIRST_INCREMENT = 1,
	THIRST_INTERVAL = 60 * 60,

	BOREDOM_INCREMENT = 1,
	BOREDOM_INTERVAL = 60 * 120,

	MOOD_RECALCULATION_INTERVAL = 60 * 30,

	SEVERE_HUNGER_PENALTY = -3,
	SEVERE_THIRST_PENALTY = -2,
	SEVERE_BOREDOM_PENALTY = -1,
	SEVERE_SADNESS_PENALTY = -1
}

return {
	NEEDS_CONSTANTS = NEEDS_CONSTANTS
}
