local RENDER_SETTINGS = {
	EMOTE_DURATION = 60,
	EMOTE_SCALE = 0.5,
	EMOTE_VERTICAL_OFFSET = -1.5,
	EMOTE_FADE_RATE = 0.0005,
	EMOTE_LIGHT_FADE_RATE = 0.0003,
	EMOTE_LIGHT_SPRITE = "utility/light_small",
	EMOTE_LIGHT_VALUE = 0.5,
	EMOTE_FORCED_MODIFIER = 1.1,
	TIME_TO_LIVE_FALLBACK = 180,
	EMOTE_SLEEPING_LIGHT_COLOR = {r = 0, g = 255, b = 0, a = 0},
	EMOTE_WAKING_LIGHT_COLOR = {r = 255, g = 255, b = 255, a = 255}
}

return {
	RENDER_SETTINGS = RENDER_SETTINGS
}
